<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PistaRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PistaRepository extends EntityRepository
{

}