<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PistaTipoRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PistaTipoRepository extends EntityRepository
{

}