<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoRepository extends EntityRepository
{
    public function getResultadosByUserId($id) {
        $resultados = $this->createQueryBuilder('r')
            ->select('r')
            ->join('r.partido','p')
            ->where('p.user = :user_id')
            ->orderBy('p.fecha', 'DESC')
            ->setParameter('user_id', $id)
            ->getQuery()
            ->getResult();

        return $resultados;
    }
}
